services:
  example:
    image: example
    build:
      context: .
      dockerfile: Dockerfile
  store:
    container_name: store
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kjsa*asf&ad(234)